### ISSUE TITLE
some scripts showing

### ISSUE THREAD

**Issue by Crystaltsn** [JemexIdeas/JemexEvent#190]
![image](https://cloud.githubusercontent.com/assets/16987335/12711156/c804ea44-c8bd-11e5-9fe7-6864d9007a66.png)

@keithwong813

**Comment by Crystaltsn** [comment]
![image](https://cloud.githubusercontent.com/assets/16987335/12712672/58525cb0-c8ca-11e5-87c4-dbc964e86591.png)

**Comment by riseno** [comment]
have been resolved

**Comment by Crystaltsn** [comment]
Script still showing

![image](https://cloud.githubusercontent.com/assets/16987335/12750701/26e81d8c-c9b9-11e5-8504-78c814b88f16.png)

**Comment by herberttse** [comment]
@Crystaltsn @riseno 
Retest today : 0204g@mail.com
Create account page - resolved
personal detail page - missing message
reg home - update info - showing the script

Linkedin message now is fine
